name: Bump Version & Release

on:
  push:
    branches:
      - master
      - develop

permissions:
  id-token: write
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: "Bump version and Release"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.COMMITIZEN_ACCESS_TOKEN }}

      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"

      - name: Set up Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pip install --constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Add Repository To Poetry
        run: |
          poetry config repositories.bssl-python-artifacts ${{ vars.GCLOUD_PYTHON_ARTIFACTS_URL }}
          poetry config keyring.enabled true

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          create_credentials_file: true

      - name: Ensure Google Keyring Auth Enabled
        run: |
          pip install keyrings.google-artifactregistry-auth
          keyring --list-backends

      - name: Poetry Publish Package to Google Cloud
        run: |
          poetry publish --build -r bssl-python-artifacts --verbose
